In [1]:
source("/rd1/user/lit/project/sORFs/sORFs.utils.R")
source("~/bin/lit_utils.R")
lib_text()
lib_plot()
setwd("/rd1/user/lit/project/sORFs/analysis/20250523_human_ms_run")

Warning message:
“程辑包‘stringr’是用R版本4.3.2 来建造的”

In [2]:
output_path <- "stat_output/S5"
create_path(output_path)

In [3]:
read_psm("./output/db_search_20250326/Trypsin/CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T_T_Slot1_46_1_4747_d/psm.tsv") -> psm

In [6]:
table(psm$Is.Unique)

false  true
30006  2486

In [9]:
psm %>% filter(grepl("ENS",Protein)) %>% filter(Is.Unique=="FALSE" | Is.Unique=="false") %>% 
  filter(!grepl("sp",Mapped.Proteins)) -> psm_non_unique

In [10]:
head(psm_non_unique)

  Spectrum
1 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.00584.00584.4
2 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.00823.00823.2
3 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.01310.01310.2
4 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.01480.01480.3
5 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.01651.01651.3
6 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.01671.01671.3
  Spectrum.File
1 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
2 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
3 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
4 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
5 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
6 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
  Peptide            Modified.Peptide  Extended.Peptide
1 AGDKETGADPGHDQSHHR                   RHQRDEEK.AGDKETGADPGHDQSHHR.QDGPGEVE
2 QPTHPIR                              .QPTHPIR.LGIAINYS
3 LSHGSAQVK                            .LSHGSAQVK.GHGKKVAD
4 MNGGHYTYSENR       M[147]NGGHYTYSENR .MNGGHYTYSENR.VEKDGIII
5 IHLSPSHHSGSK                         .IHLSPSHHSGSK.AASIHWTS
6 IHLSPSHHSGSK                         .IHLSPSHHSGSK.AASIHWTS
  Prev.AA Next.AA Peptide.Length Charge Retention ⋯ Purity Is.Unique
1 K       Q       18             4      336.2110  ⋯ 0      false
2 M       L        7             2      359.7659  ⋯ 0      false
3 -       G        9             2      372.6732  ⋯ 0      false
4 -       V       12             3      376.1995  ⋯ 0      false
5 -       A       12             3      380.8958  ⋯ 0      false
6 -       A       12             3      382.0664  ⋯ 0      false
  Protein
1 ENST00000558505.5-chr15:40290064-40290720
2 ENST00000307630.5-chr7:76329576-76329828
3 ENST00000472694.1+chr16:176977-177411
4 ENST00000377493.9+chr1:7977728-7985054
5 ENST00000375549.8+chr11:112087948-112094970
6 ENST00000375549.8+chr11:112087948-112094970
  Protein.ID
1 ENST00000558505.5-chr15:40290064-40290720 PE=4
2 ENST00000307630.5-chr7:76329576-76329828 PE=4
3 ENST00000472694.1+chr16:176977-177411 PE=4
4 ENST00000377493.9+chr1:7977728-7985054 PE=4
5 ENST00000375549.8+chr11:112087948-112094970 PE=4
6 ENST00000375549.8+chr11:112087948-112094970 PE=4
  Entry.Name                                       Gene
1 ENST00000558505.5-chr15:40290064-40290720 PE=4
2 ENST00000307630.5-chr7:76329576-76329828 PE=4
3 ENST00000472694.1+chr16:176977-177411 PE=4
4 ENST00000377493.9+chr1:7977728-7985054 PE=4
5 ENST00000375549.8+chr11:112087948-112094970 PE=4
6 ENST00000375549.8+chr11:112087948-112094970 PE=4
  Protein.Description                              Mapped.Genes
1 ENST00000558505.5-chr15:40290064-40290720 PE=4
2 ENST00000307630.5-chr7:76329576-76329828 PE=4
3 ENST00000472694.1+chr16:176977-177411 PE=4
4 ENST00000377493.9+chr1:7977728-7985054 PE=4
5 ENST00000375549.8+chr11:112087948-112094970 PE=4
6 ENST00000375549.8+chr11:112087948-112094970 PE=4
  Mapped.Proteins
1 ENST00000558505.5-chr15:40290064-40290678, ENST00000558505.5-chr15:40290064-40290690, ENST00000558505.5-chr15:40290064-40290762, ENST00000558505.5-chr15:40290064-40290771, ENST00000558505.5-chr15:40290064-40290777, ENST00000558505.5-chr15:40290064-40290780, ENST00000558505.5-chr15:40290064-40290786, ENST00000558505.5-chr15:40290064-40290789, ENST00000558505.5-chr15:40290064-40290816, ENST00000558505.5-chr15:40290064-40290822, ENST00000558505.5-chr15:40290064-40290825, ENST00000558505.5-chr15:40290064-40290834, ENST00000558505.5-chr15:40290064-40291303, ENST00000559381.5-chr15:40290064-40291054
2 ENST00000415292.1+chr10:23137400-23137661, ENST00000445359.1+chr9:38643515-38643698, ENST00000471374.1+chr22:31956543-31956792, ENST00000474715.1-chr2:9585285-9588269, ENST00000479421.5+chr20:44905026-44906438, ENST00000480304.5-chr8:100923942-100924239, ENST00000517727.5-chr8:100924110-100924239, ENST00000522542.5-chr8:100920692-100924239, ENST00000631616.1+chr20:44905026-44905158
3 ENST00000482565.1+chr16:173173-173600, ENST00000487791.1+chr16:176977-177265
4 ENST00000377493.9+chr1:7977725-7985054
5 ENST00000414693.1-chr1:25294163-25294499, ENST00000525987.5+chr11:112087948-112170527, ENST00000526592.5+chr11:112087948-112093197, ENST00000528021.6+chr11:112087948-112119292, ENST00000528182.5+chr11:112087948-112094893, ENST00000530923.5+chr11:112087948-112091079
6 ENST00000414693.1-chr1:25294163-25294499, ENST00000525987.5+chr11:112087948-112170527, ENST00000526592.5+chr11:112087948-112093197, ENST00000528021.6+chr11:112087948-112119292, ENST00000528182.5+chr11:112087948-112094893, ENST00000530923.5+chr11:112087948-112091079
  Sample
1 21pcw_1_PAGE_T_T
2 21pcw_1_PAGE_T_T
3 21pcw_1_PAGE_T_T
4 21pcw_1_PAGE_T_T
5 21pcw_1_PAGE_T_T
6 21pcw_1_PAGE_T_T

In [11]:
unfold_nonUnique <- function(df){
    # 分组并且展开
    df$Group_id <- 1:nrow(df)
    df %>% separate_rows(`Mapped.Proteins`, convert = TRUE,sep=", ") -> tmp
    tmp %>% mutate(Protein=`Mapped.Proteins`,
                   `Protein.ID`=`Mapped.Proteins`,
                   Gene=`Mapped.Proteins`,
                   `Entry.Name`=`Mapped.Proteins`,
                   `Protein.Description`=`Mapped.Proteins`) -> tmp_1
    rbind(df,tmp_1) -> df_unfold
    return(df_unfold)
}

In [12]:
psm_non_unique -> df
unfold_nonUnique(df) -> df_unfold

In [14]:
df_unfold %>% arrange(Group_id) %>% head(5)

  Spectrum
1 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.00584.00584.4
2 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.00584.00584.4
3 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.00584.00584.4
4 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.00584.00584.4
5 CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.00584.00584.4
  Spectrum.File
1 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
2 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
3 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
4 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
5 interact-CAD20241224licq_BSEP_DDA_60min_21pcw_1_PAGE_T-T_Slot1-46_1_4747.pep.xml
  Peptide            Modified.Peptide Extended.Peptide
1 AGDKETGADPGHDQSHHR                  RHQRDEEK.AGDKETGADPGHDQSHHR.QDGPGEVE
2 AGDKETGADPGHDQSHHR                  RHQRDEEK.AGDKETGADPGHDQSHHR.QDGPGEVE
3 AGDKETGADPGHDQSHHR                  RHQRDEEK.AGDKETGADPGHDQSHHR.QDGPGEVE
4 AGDKETGADPGHDQSHHR                  RHQRDEEK.AGDKETGADPGHDQSHHR.QDGPGEVE
5 AGDKETGADPGHDQSHHR                  RHQRDEEK.AGDKETGADPGHDQSHHR.QDGPGEVE
  Prev.AA Next.AA Peptide.Length Charge Retention ⋯ Is.Unique
1 K       Q       18             4      336.211   ⋯ false
2 K       Q       18             4      336.211   ⋯ false
3 K       Q       18             4      336.211   ⋯ false
4 K       Q       18             4      336.211   ⋯ false
5 K       Q       18             4      336.211   ⋯ false
  Protein
1 ENST00000558505.5-chr15:40290064-40290720
2 ENST00000558505.5-chr15:40290064-40290678
3 ENST00000558505.5-chr15:40290064-40290690
4 ENST00000558505.5-chr15:40290064-40290762
5 ENST00000558505.5-chr15:40290064-40290771
  Protein.ID
1 ENST00000558505.5-chr15:40290064-40290720 PE=4
2 ENST00000558505.5-chr15:40290064-40290678
3 ENST00000558505.5-chr15:40290064-40290690
4 ENST00000558505.5-chr15:40290064-40290762
5 ENST00000558505.5-chr15:40290064-40290771
  Entry.Name
1 ENST00000558505.5-chr15:40290064-40290720 PE=4
2 ENST00000558505.5-chr15:40290064-40290678
3 ENST00000558505.5-chr15:40290064-40290690
4 ENST00000558505.5-chr15:40290064-40290762
5 ENST00000558505.5-chr15:40290064-40290771
  Gene
1
2 ENST00000558505.5-chr15:40290064-40290678
3 ENST00000558505.5-chr15:40290064-40290690
4 ENST00000558505.5-chr15:40290064-40290762
5 ENST00000558505.5-chr15:40290064-40290771
  Protein.Description                            Mapped.Genes
1 ENST00000558505.5-chr15:40290064-40290720 PE=4
2 ENST00000558505.5-chr15:40290064-40290678
3 ENST00000558505.5-chr15:40290064-40290690
4 ENST00000558505.5-chr15:40290064-40290762
5 ENST00000558505.5-chr15:40290064-40290771
  Mapped.Proteins
1 ENST00000558505.5-chr15:40290064-40290678, ENST00000558505.5-chr15:40290064-40290690, ENST00000558505.5-chr15:40290064-40290762, ENST00000558505.5-chr15:40290064-40290771, ENST00000558505.5-chr15:40290064-40290777, ENST00000558505.5-chr15:40290064-40290780, ENST00000558505.5-chr15:40290064-40290786, ENST00000558505.5-chr15:40290064-40290789, ENST00000558505.5-chr15:40290064-40290816, ENST00000558505.5-chr15:40290064-40290822, ENST00000558505.5-chr15:40290064-40290825, ENST00000558505.5-chr15:40290064-40290834, ENST00000558505.5-chr15:40290064-40291303, ENST00000559381.5-chr15:40290064-40291054
2 ENST00000558505.5-chr15:40290064-40290678
3 ENST00000558505.5-chr15:40290064-40290690
4 ENST00000558505.5-chr15:40290064-40290762
5 ENST00000558505.5-chr15:40290064-40290771
  Sample           Group_id
1 21pcw_1_PAGE_T_T 1
2 21pcw_1_PAGE_T_T 1
3 21pcw_1_PAGE_T_T 1
4 21pcw_1_PAGE_T_T 1
5 21pcw_1_PAGE_T_T 1

In [16]:
n_distinct(df_unfold$Protein)
n_distinct(df_unfold$Peptide)

[1] 3042

[1] 556