In [1]:
source("/home/user/data2/lit/bin/lit_utils.R")
source("/home/user/data3/lit/project/sORFs/sORFs.utils.R")
lib_text()
lib_plot()

In [7]:
fread_c("../../MS_res_from_Galaxy/HLA/MHC-I-peptide.tsv") -> hla_1
head(hla_1)

  Peptide      Prev AA Next AA Peptide Length Protein Start Protein End Charges
1 AAMLDTVVFK   L       -       10             301           310         2
2 AAPGVDLSRIL  D       N       11             274           284         2
3 ADINGLRQV    D       L        9             255           263         2
4 ADINGLRQVL   D       D       10             255           264         2
5 ADINGLRQVLD  D       N       11             255           265         2
6 ADINGLRQVLDN D       L       12             255           266         2
  Probability Spectral Count Intensity Assigned Modifications
1 0.9968      1              0
2 0.9429      1              0
3 0.9660      1              0
4 0.9962      2              0
5 0.9990      2              0
6 1.0000      4              0
  Observed Modifications Protein
1 NA                     PB.25661.5:chr2:+|19|1576:329:1262|canonical|ATG
2 NA                     sp|Cont_P02533|K1C14_HUMAN
3 NA                     sp|P35527|K1C9_HUMAN
4 NA                     sp|P35527|K1C9_HUMAN
5 NA                     sp|P35527|K1C9_HUMAN
6 NA                     sp|P35527|K1C9_HUMAN
  Protein ID
1 PB.25661.5:chr2:+|19|1576:329:1262|canonical|ATG
2 Cont_P02533
3 P35527
4 P35527
5 P35527
6 P35527
  Entry Name                                       Gene
1 PB.25661.5:chr2:+|19|1576:329:1262|canonical|ATG
2 K1C14_HUMAN                                      KRT14
3 K1C9_HUMAN                                       KRT9
4 K1C9_HUMAN                                       KRT9
5 K1C9_HUMAN                                       KRT9
6 K1C9_HUMAN                                       KRT9
  Protein Description
1 PB.25661.5:chr2:+|19|1576:329:1262|canonical|ATG
2 Keratin, type I cytoskeletal 14
3 Keratin, type I cytoskeletal 9
4 Keratin, type I cytoskeletal 9
5 Keratin, type I cytoskeletal 9
6 Keratin, type I cytoskeletal 9
  Mapped Genes
1
2 KRT16, KRT17, Krt16, Krt17, Krt42
3
4
5
6
  Mapped Proteins
1
2 sp|Cont_P08779|K1C16_HUMAN, sp|Cont_Q04695|K1C17_HUMAN, sp|Cont_Q6IFX2|K1C42_MOUSE, sp|Cont_Q9QWL7|K1C17_MOUSE, sp|Cont_Q9Z2K1|K1C16_MOUSE
3
4
5
6

In [16]:
filter(hla_1,`Mapped Proteins`=="") %>% distinct(Protein,Peptide) %>% count(Protein) ->tmp
tmp[!grepl("canonical",tmp$Protein),]

    Protein                                             n
15  PB.14478.290:chr14:+|5|3546:48:2517|noncoding|ATG     1
34  PB.20259.78:chr18:+|66|2978:1021:1351|noncoding|ATG   1
63  PB.2777.12:chr1:-|1|3376:18:120|noncoding|CTG         1
75  PB.33814.11:chr4:+|10|1305:157:1111|noncoding|ATG     1
80  PB.351.42:chr1:-|11|2734:130:223|uORF|ATG             1
82  PB.35729.1:chr4:-|14|1914:247:319|noncoding|ATG       1
99  PB.42204.31:chr6:+|79|2210:931:1000|dORF|ATG          1
104 PB.4725.100:chr10:-|3|2751:95:2057|noncoding|ATG      1
105 PB.47278.202:chr8:-|16|4182:309:438|noncoding|ATG     1
107 PB.48537.177:chr8:-|17|2343:245:341|noncoding|ATG     1
114 PB.50739.79:chr9:+|54|4672:682:1411|noncoding|ATG     1
131 sp|Cont_P02533|K1C14_HUMAN                            5
132 sp|Cont_P05787|K2C8_HUMAN                             2
133 sp|Cont_P07744|K2C4_MOUSE                             1
134 sp|Cont_P13647|K2C5_HUMAN                             6
135 sp|Cont_P19001|K1C19_MOUSE                            1
136 sp|Cont_Q86YZ3|HORN_HUMAN                             5
137 sp|Cont_Q8IUC2|KRA81_HUMAN                            1
138 sp|O82803|SRPP_HEVBR                                  7
139 sp|P00761|TRYP_PIG                                    3
140 sp|P01012|OVAL_CHICK                                 87
141 sp|P02662|CASA1_BOVIN                                 5
142 sp|P02666|CASB_BOVIN                                  6
143 sp|P02768|ALBU_HUMAN                                 24
144 sp|P04264|K2C1_HUMAN                                 82
145 sp|P13645|K1C10_HUMAN                                28
146 sp|P15252|REF_HEVBR                                   4
147 sp|P35527|K1C9_HUMAN                                117
148 sp|P35908|K22E_HUMAN                                 29
149 sp|P69905|HBA_HUMAN                                   5